version: 0.2

phases:
  pre_build:
    commands:
      - pip install awscli --upgrade --user
      - echo Logging in to Amazon ECR...
      - echo 'aws --version'
      - $(aws ecr get-login --no-include-email --region us-east-1)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t anagram .
      - docker tag anagram:latest 764784637549.dkr.ecr.us-east-1.amazonaws.com/anagram:latest 
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 764784637549.dkr.ecr.us-east-1.amazonaws.com/anagram:latest
  artifacts:
    files: imagedefinitions.json    
